language: ruby
cache: bundler
rvm: 2.4.0
bundler_args: --without production

before_install:
  - cd rottenpotatoes
  - gem install bundler:1.17.3

script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle exec cucumber
